server/config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  get "contact" => "contact#index"
  post "contact_submit" => "contact#create", as: "contact_submit"
  get'faq' => "faq#index"
  # resources :questions, namespace: ':admin'
  # get 'questions' => 'questions#index'
  # get 'questions/new' => 'questions#new', as: :new_question
  # post 'questions' => 'questions#create'
  # delete 'questions/:id' => "questions#destroy"
  # get 'questions/:id' => "questions#show", as: :question
  # get 'questions/:id/edit' => "questions#edit", as: :edit_question
  # patch 'questions/:id' => "questions#update"
  
  # namespace :admin do
  #   resources :questions
  # end
  # scope '/admin' do
  #   resources :questions
  # end

  # ROUTES FOR QUESTIONS
  # get('/questions', to:"questions#index")
  # get('/questions/new', to: "questions#new", as: :new_question)
  # post('/questions', to: "questions#create")

  # get('/questions/:id', to: 'questions#show', as: :question)
  # # http://localhost:3000/questions/9
  # delete("/questions/:id",to: "questions#destroy")
  # get('/questions/:id/edit', to: "questions#edit", as: :edit_question)
  # patch('/questions/:id', to: "questions#update")


  # resources will built a CRUD RESTfull routes.(all of the above routes)
  # It assumes that there will be a contoller name as a first argument, pluralized and PascalCase
  # PascalCase
  resources :questions do
    resources :likes, shallow: true, only: [:create, :destroy]

    get :liked, on: :collection
    # All the resources in this block will be prefixed by this👇🏻
    # /questions/:question_id 
    # So we can now grab question_id from params like params[:question_id]

    resources :answers, only:[:create, :destroy] # this will only generate routes for :create and :destroy action
    # /questions/:question_id/answers/:id
    # /questions/:question_id/answers/:id/edit 
  end

  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  # resource is singular instead of resources
  # Unlike resources, resource will create routes that do CRUD operations only on one thing. 
  # There will be no index routes and no route will have an :id wildcard
  # Even with singular resource controller will still be plural.

  resources :job_posts, only: [:new, :create, :show, :index, :edit, :update, :destroy]
   # The namespace method in Rails routes makes it so that 
  # your app will automatically look in a directory api
  # and then in a sub directory v1 for QuestionController

  # the options 'defaults: {format: :json}' will set 'json' as the default response
  # format for all the routes contained within the block
  # /api/v1/questions
  namespace :api, defaults: {format: :json} do # we can set default response format of the block
    namespace :v1 do
      resources :questions, only:[:index, :show, :update, :create, :destroy]
      resource :session, only:[:create, :destroy]
      get('/current_user', to: 'sessions#get_current_user')
      resources :users, only: [:create]
    end
    # namespace :v2 do
    #   resources :questions
    # end
  end

end

server/app/views/shared/_alerts.html.erb
<%#= flash[:notice] || flash[:alert] %>

<% if flash[:notice].present? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times; </span>
    </button>
</div>
<% elsif flash[:alert].present? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert]  %> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        &times;
    </button>

</div>
<% end %>

server/app/views/shared/_form.html.erb
<%= form_with model:@question, local: true do |form| %>
<% if @question.errors.present? %>
<%= @question.errors.full_messages.join(', ')%>
<% end %>
<div>
    <%= form.label :title  %> 
    <%= form.text_field :title  %> 
</div>
<div>
    <%= form.label :body  %>
    <%= form.text_area :body, cols:50 ,rows:5  %>  
</div>
<div>
   <%= form.label :tag_names  %>  
   <%= form.text_field :tag_names  %> 
</div>
<%=form.submit  %> 

<% end %>

<script>
$(function(){
    $('#question_tag_names').selectize({
        delimeter:',',
        persist: false,
        labelField:'name', //Coulmn name in db
        valueField:'name',//Coulmn name in db
        searchField:'name',//Coulmn name in db
        options: <%= Tag.select(:name).to_json(except:[:id]).html_safe %>,
        // The above line selects only names from tags table and converts them to a json array of objects without including ids and makes sure its a safe_html string
        // options:[{"name":"first tag"},{"name":"second tag"},{"name":"third tag"},{"name":"fourth tag"},{"name":"fifth tag"}, ....]
        
        create :function(input){
            return{
                name:input
            }
        }
    })
})

</script>

server/app/views/shared/_navbar.html.erb

<nav class="navbar navbar-expand navbar-dark bg-dark justify-content-between py-0">
    <%= link_to "Home", root_path, :class=>"navbar-brand mr-auto" %>
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Questions", questions_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
            <%= link_to 'New Question', new_question_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
            <%= link_to "Contact", contact_path, :class=>"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "FAQ", faq_path, :class=>"nav-link" %></li>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Liked Questions', liked_questions_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
        <span class="navbar-text">| Hello <%= current_user.full_name.split.map(&:capitalize).join(' ') %> |</span>
        </li>
        <li class="nav-item">
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: 'Are you sure you want to log out?'}, :class=>"nav-link"
         %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Sign In", new_session_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, :class=>"nav-link" %></li>
        </li>
        <% end %>
      </ul>
  </nav>